import Head from "next/head";
import Form from "../src/components/Form/Form";
import GridHelper from "../src/components/Layout/Grid/GridHelper";
import GlobalStyle from "../src/styles/globalStyle";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Old+Standard+TT&family=Rajdhani:wght@500&display=swap"
          rel="stylesheet"
        />
      </Head>
      <GlobalStyle />
      <GridHelper />
      <Form />
    </>
  );
}
